services:
  api:
    image: desafio:api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    depends_on:
      - postgresql
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/app
    networks:
      - desafio-network

  front:
    image: desafio:front
    build:
      context: .
      dockerfile: ./docker/Dockerfile.front
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./front/:/app
    networks:
      - desafio-network

  postgresql:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=desafio"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge
